# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 842daa6fc00411e0ee017090de07e2d5c5b102eee4d1e11131bfe84d241992cc351571225195348f6526efc312aaa23c11e139875e3f9f7018111cf86537fbc0

test:
  secret_key_base: 859ea01488a305a4f2fac84d5d4e49deddb7ace5143109e875d2532a90323922d94384b5bef9c3ef00ba04cf00a3ec9f112dc678738512f3a31cfda436032082

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
